import { StaticImageData } from "next/image";
import image1 from "@/public/images/image1.png";
import image2 from "@/public/images/image2.png";
import image3 from "@/public/images/image3.png";
import image4 from "@/public/images/image1.png";

export type product = {
  id: string; // string not number
  name: string;
  price: number;
  image: StaticImageData;
  alt: string;
  category: string;
  description: string;
};

export const Product: product[] = [
  {
    id: "1",
    name: "Syltherine",
    image: image1,
    category: "Stylish cafe chair",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 1",
  },
  {
    id: "2",
    name: "Syltherine",
    image: image2,
    category: "Luxury big sofa",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 2",
  },
  {
    id: "3",
    name: "Syltherine",
    image: image3,
    category: "Outdoor bar table and stool",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 3",
  },
  {
    id: "4",
    name: "Syltherine",
    image: image4,
    category: "Small mug",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 4",
  },
  {
    id: "5",
    name: "Syltherine",
    image: image2,
    category: "cute bed set",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 5",
  },
  {
    id: "6",
    name: "Syltherine",
    image: image3,
    category: "Stylish cafe chair",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 6",
  },
  {
    id: "7",
    name: "Syltherine",
    image: image1,
    category: "Stylish cafe chair",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 7",
  },
  {
    id: "8",
    name: "Syltherine",
    image: image2,
    category: "Stylish cafe chair",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 8",
  },
  {
    id: "9",
    name: "Syltherine",
    image: image2,
    category: "Stylish cafe chair",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 8",
  },
  {
    id: "10",
    name: "Syltherine",
    image: image2,
    category: "Stylish cafe chair",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 8",
  },
  {
    id: "11",
    name: "Syltherine",
    image: image2,
    category: "Stylish cafe chair",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 8",
  },
  {
    id: "12",
    name: "Syltherine",
    image: image2,
    category: "Stylish cafe chair",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 8",
  },
  {
    id: "13",
    name: "Syltherine",
    image: image2,
    category: "Stylish cafe chair",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 8",
  },
  {
    id: "14",
    name: "Syltherine",
    image: image2,
    category: "Stylish cafe chair",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 8",
  },
  {
    id: "15",
    name: "Syltherine",
    image: image2,
    category: "Stylish cafe chair",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 8",
  },
  {
    id: "16",
    name: "Syltherine",
    image: image2,
    category: "Stylish cafe chair",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 8",
  },
  {
    id: "17",
    name: "Syltherine",
    image: image2,
    category: "Stylish cafe chair",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 8",
  },
  {
    id: "18",
    name: "Syltherine",
    image: image2,
    category: "Stylish cafe chair",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 8",
  },
  {
    id: "19",
    name: "Syltherine",
    image: image2,
    category: "Stylish cafe chair",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 8",
  },
  {
    id: "20",
    name: "Syltherine",
    image: image2,
    category: "Stylish cafe chair",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 8",
  },
  {
    id: "21",
    name: "Syltherine",
    image: image2,
    category: "Stylish cafe chair",
    description: "hjnxknjxnhxhxxxjj",
    price: 250000,
    alt: "Product 8",
  },
];
